# Generated by Django 5.2.13 on 2026-07-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('order_new', 'New order'), ('order_status', 'Order status'), ('price_alert', 'Price alert'), ('portfolio', 'Portfolio'), ('vendor_kyc', 'Vendor KYC'), ('kyc_status', 'Customer KYC'), ('kyb_status', 'Vendor KYB')], max_length=32),
        ),
    ]
