# Generated by Django 5.2.13 on 2026-07-18 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('order_new', 'New order'), ('order_status', 'Order status'), ('price_alert', 'Price alert'), ('portfolio', 'Portfolio'), ('vendor_kyc', 'Vendor KYC'), ('kyc_status', 'Customer KYC'), ('kyb_status', 'Vendor KYB'), ('admin_broadcast', 'Admin broadcast')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdminBroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('custom', 'Custom message'), ('live_price', 'Live price')], default='custom', max_length=16)),
                ('audience', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('guests_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
