# Generated by Django 5.2.13 on 2026-08-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_phone_verified_kyc_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='outcome',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='sent_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
