# Generated by Django 5.2.13 on 2026-07-29 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0051_v7_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('gold_principal', 'Gold principal'), ('delivery_fee', 'Delivery fee'), ('sellback_funding_in', 'Sell-back funding (vendor → Cridora)'), ('sellback_disbursement_out', 'Sell-back disbursement (Cridora → customer)')], max_length=40)),
                ('provider_key', models.CharField(choices=[('manual_aani', 'Manual Aani'), ('stripe', 'Stripe'), ('telr', 'Telr')], max_length=32)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('funds_source', models.CharField(choices=[('dealer', 'Dealer'), ('customer', 'Customer'), ('cridora_fee_revenue', 'Cridora fee revenue')], default='customer', max_length=32)),
                ('evidence_ref', models.CharField(blank=True, default='', max_length=512)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='payment_evidence/')),
                ('customer_proxy', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_txns_confirmed', to=settings.AUTH_USER_MODEL)),
                ('delivery_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='users.deliveryrequest')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_txns_initiated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='users.order')),
                ('paired_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_disbursements', to='payments.paymenttransaction')),
                ('sell_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='users.sellorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_key', 'status'], name='payments_pa_provide_5cb28d_idx'), models.Index(fields=['fee_type', 'status'], name='payments_pa_fee_typ_06110f_idx')],
            },
        ),
    ]
