# Generated by Django 6.0.4 on 2026-04-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('country', models.CharField(default='UAE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_desc', models.TextField()),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('rate_per_gram', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_included', models.BooleanField(default=False)),
                ('buyback_per_gram', models.DecimalField(decimal_places=4, max_digits=12)),
                ('in_stock', models.BooleanField(default=True)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='metals.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
