/** Bilingual copy for Atelier Theme Sheet v3.1 */

export const TABS = [
  { id: 'components', en: 'Components & UI', ar: 'المكوّنات والواجهة' },
  { id: 'rates', en: 'Live Rates & Simulator', ar: 'الأسعار والمحاكي' },
  { id: 'states', en: 'System States', ar: 'حالات النظام' },
  { id: 'tables', en: 'Tables & Accordions', ar: 'الجداول والأكورديون' },
  { id: 'flags', en: 'Flags & Icons', ar: 'الأعلام والأيقونات' },
]

export const copy = {
  en: {
    brand: 'Cridora Atelier',
    subtitle: 'UI/UX Theme Sheet · Version 3.1',
    tagline: 'Cinematic gold-standard design system — components, rates, states, and bilingual patterns.',
    liveFeed: 'LBMA Live Atelier Feed',
    spread: 'Spread',
    lowVol: 'Low volatility',
    goldLabel: 'Gold Au 24K',
    silverLabel: 'Silver Ag 999',
    langEn: 'EN',
    langAr: 'عربي',
    sectionButtons: 'Buttons & Touch Targets',
    sectionBadges: 'Status Badges & Pills',
    sectionCards: 'Atelier Vault Asset Cards',
    sectionInputs: 'Interactive Inputs & Controls',
    sectionFaq: 'Content Accordions / FAQ',
    btnPrimary: 'Primary Atelier Gold',
    btnSecondary: 'Secondary Surface',
    btnOutline: 'Outline Border',
    btnSuccess: 'Success Action',
    btnDanger: 'Destructive',
    btnDisabled: 'Disabled',
    badgeAllocated: 'Allocated',
    badgePending: 'Pending Verification',
    badgeLiq: 'Liquidation Warning',
    badgeCbu: 'Central Bank Regulated',
    badgeTier: 'Atelier Standard Tier',
    cardGoldTitle: '50g 24K Gold Bar',
    cardGoldMeta: 'LBMA Good Delivery · Allocated',
    cardSilverTitle: '500g Fine Silver',
    cardSilverMeta: 'Secure storage · DMCC',
    searchPh: 'Search vault assets, refs…',
    toggleSms: 'SMS instant alerts',
    sliderLabel: 'Portfolio weight simulator',
    sliderHint: '5g – 500g Au · live valuation',
    yieldLabel: 'Projected yield',
    valuation: 'Estimated value',
    faq1q: 'What is allocated physical bullion?',
    faq1a: 'Metal held in your name at a licensed vault — serialised, insured, and redeemable. Cridora never takes title.',
    faq2q: 'How is the LBMA benchmark rate calculated?',
    faq2a: 'Atelier surfaces indicative AED/g from live spot feeds, converted and displayed for Gold 24K and Silver 999.',
    faq3q: 'How does physical home delivery work?',
    faq3a: 'After purchase, arrange collection or delivery with the selling dealer. Weight and purity are verified at handover.',
    metalGold: 'Gold Spot (Au)',
    metalSilver: 'Silver Spot (Ag)',
    chartTitle: 'Interactive rate canvas',
    high1y: '1Y High',
    low1y: '1Y Low',
    ret1y: '1Y Return',
    skeleton: 'Skeleton loading',
    spinnerTitle: 'Connecting to Aani…',
    spinnerDesc: 'Active execution — instant payment gateway handshake in progress.',
    offlineTitle: 'No Internet Connection',
    offlineDesc: 'Live rates and vault actions need a connection. Check your network and try again.',
    retry: 'Retry',
    notFoundTitle: '404 · Page Not Found',
    notFoundDesc: 'This route is not part of the Atelier theme sheet.',
    returnHome: 'Return home',
    ledgerTitle: 'Transaction ledger',
    colRef: 'Ref',
    colType: 'Type',
    colWeight: 'Weight / Asset',
    colAmount: 'Amount',
    colStatus: 'Status',
    colAction: 'Audit',
    expandHint: 'Tap a row for provenance',
    auditDate: 'Execution',
    auditVault: 'Vault',
    auditSerial: 'Serial',
    vaultLoc: 'DMCC Gold Centre, Dubai',
    countriesTitle: 'Global regional support',
    iconsTitle: 'Lucide iconography registry',
    viewLedger: 'View',
  },
  ar: {
    brand: 'كريدورا أتيليه',
    subtitle: 'ورقة نظام التصميم · الإصدار 3.1',
    tagline: 'نظام تصميم سينمائي بمعيار الذهب — مكوّنات، أسعار، حالات، وأنماط ثنائية اللغة.',
    liveFeed: 'بث أتيليه المباشر · LBMA',
    spread: 'الفرق',
    lowVol: 'تقلب منخفض',
    goldLabel: 'ذهب عيار 24',
    silverLabel: 'فضة 999',
    langEn: 'EN',
    langAr: 'عربي',
    sectionButtons: 'الأزرار وأهداف اللمس',
    sectionBadges: 'شارات الحالة',
    sectionCards: 'بطاقات أصول الخزنة',
    sectionInputs: 'المدخلات والتحكم',
    sectionFaq: 'الأسئلة الشائعة',
    btnPrimary: 'ذهبي أساسي',
    btnSecondary: 'سطح ثانوي',
    btnOutline: 'حدود خارجية',
    btnSuccess: 'إجراء ناجح',
    btnDanger: 'إجراء خطر',
    btnDisabled: 'معطّل',
    badgeAllocated: 'مخصّص',
    badgePending: 'بانتظار التحقق',
    badgeLiq: 'تحذير تصفية',
    badgeCbu: 'خاضع للبنك المركزي',
    badgeTier: 'مستوى أتيليه القياسي',
    cardGoldTitle: 'سبيكة ذهب 50غ عيار 24',
    cardGoldMeta: 'LBMA · مخصّص',
    cardSilverTitle: 'فضة نقية 500غ',
    cardSilverMeta: 'تخزين آمن · مركز دبي للسلع',
    searchPh: 'ابحث عن الأصول أو المراجع…',
    toggleSms: 'تنبيهات فورية عبر الرسائل',
    sliderLabel: 'محاكي وزن المحفظة',
    sliderHint: '5غ – 500غ ذهب · تقييم مباشر',
    yieldLabel: 'العائد المتوقع',
    valuation: 'القيمة التقديرية',
    faq1q: 'ما هو السبائك المادية المخصّصة؟',
    faq1a: 'معدن محفوظ باسمك في خزنة مرخّصة — مرقّم ومؤمّن وقابل للاسترداد. كريدورا لا تمتلك المعدن.',
    faq2q: 'كيف يُحسب سعر معيار LBMA؟',
    faq2a: 'يعرض أتيليه أسعارًا إرشادية بالدرهم للجرام من موجزات السوق الحية للذهب عيار 24 والفضة 999.',
    faq3q: 'كيف يتم التوصيل المنزلي؟',
    faq3a: 'بعد الشراء، رتّب الاستلام أو التوصيل مع التاجر البائع. يُتحقق من الوزن والنقاء عند التسليم.',
    metalGold: 'ذهب فوري (Au)',
    metalSilver: 'فضة فورية (Ag)',
    chartTitle: 'لوحة الأسعار التفاعلية',
    high1y: 'أعلى سعر لسنة',
    low1y: 'أدنى سعر لسنة',
    ret1y: 'عائد سنة',
    skeleton: 'تحميل هيكلي',
    spinnerTitle: 'الاتصال بـ Aani…',
    spinnerDesc: 'تنفيذ نشط — جارٍ الربط ببوابة الدفع الفوري.',
    offlineTitle: 'لا يوجد اتصال بالإنترنت',
    offlineDesc: 'الأسعار الحية وإجراءات الخزنة تحتاج اتصالًا. تحقق من الشبكة وأعد المحاولة.',
    retry: 'إعادة المحاولة',
    notFoundTitle: '404 · الصفحة غير موجودة',
    notFoundDesc: 'هذا المسار ليس جزءًا من ورقة سمة أتيليه.',
    returnHome: 'العودة للرئيسية',
    ledgerTitle: 'سجل المعاملات',
    colRef: 'مرجع',
    colType: 'النوع',
    colWeight: 'الوزن / الأصل',
    colAmount: 'المبلغ',
    colStatus: 'الحالة',
    colAction: 'تدقيق',
    expandHint: 'اضغط صفًا لعرض المصدر',
    auditDate: 'التنفيذ',
    auditVault: 'الخزنة',
    auditSerial: 'الرقم التسلسلي',
    vaultLoc: 'مركز دبي للسلع المتعددة — الذهب',
    countriesTitle: 'الدعم الإقليمي العالمي',
    iconsTitle: 'سجل أيقونات Lucide',
    viewLedger: 'عرض',
  },
}

export const COUNTRIES = [
  { flag: '🇦🇪', name: { en: 'United Arab Emirates', ar: 'الإمارات' }, dial: '+971', ccy: 'AED' },
  { flag: '🇸🇦', name: { en: 'Saudi Arabia', ar: 'السعودية' }, dial: '+966', ccy: 'SAR' },
  { flag: '🇨🇭', name: { en: 'Switzerland', ar: 'سويسرا' }, dial: '+41', ccy: 'CHF' },
  { flag: '🇬🇧', name: { en: 'United Kingdom', ar: 'المملكة المتحدة' }, dial: '+44', ccy: 'GBP' },
  { flag: '🇺🇸', name: { en: 'United States', ar: 'الولايات المتحدة' }, dial: '+1', ccy: 'USD' },
  { flag: '🇸🇬', name: { en: 'Singapore', ar: 'سنغافورة' }, dial: '+65', ccy: 'SGD' },
  { flag: '🇶🇦', name: { en: 'Qatar', ar: 'قطر' }, dial: '+974', ccy: 'QAR' },
  { flag: '🇰🇼', name: { en: 'Kuwait', ar: 'الكويت' }, dial: '+965', ccy: 'KWD' },
]

export const LEDGER = [
  { ref: 'CRD-88421', type: { en: 'Buy', ar: 'شراء' }, weight: '50g Au 24K', amount: 23912, status: 'allocated', serial: 'AU-DMCC-50-9182' },
  { ref: 'CRD-88390', type: { en: 'Storage', ar: 'تخزين' }, weight: '500g Ag 999', amount: 3436, status: 'pending', serial: 'AG-DMCC-500-4410' },
  { ref: 'CRD-88211', type: { en: 'Sell back', ar: 'بيع عكسي' }, weight: '10g Au 24K', amount: 4720, status: 'allocated', serial: 'AU-DMCC-10-2201' },
  { ref: 'CRD-88102', type: { en: 'Delivery', ar: 'توصيل' }, weight: '100g Au 24K', amount: 47825, status: 'warning', serial: 'AU-DMCC-100-7733' },
]
