/**
 * Illustrative composite fee models — not offers from named brands.
 * Buy-side processing is left at 0 so Cridora Assurance is also omitted in the matrix.
 */

export const STATIC_COMPETITORS = [
  {
    id: 'enbd',
    name: 'Major UAE Bank A (gold account)',
    category: 'banks',
    badge: 'Spread + custody + exit fees',
    buySpreadPct: 0.015,
    buyFeePct: 0.0,
    buyFixedFee: 0.15,
    annualCustodyPct: 0.002625,
    sellSpreadPct: 0.015,
    sellFeePct: 0.0,
    sellExitFeePct: 0.00525,
    sellFixedFee: 52.5,
    notes: 'Illustrative bank-style friction with custody and exit assumptions.',
  },
  {
    id: 'mashreq',
    name: 'Digital Bank App (gold account)',
    category: 'banks',
    badge: 'Spread + custody',
    buySpreadPct: 0.016,
    buyFeePct: 0.0,
    buyFixedFee: 0.0,
    annualCustodyPct: 0.002,
    sellSpreadPct: 0.016,
    sellFeePct: 0.0,
    sellExitFeePct: 0.0025,
    sellFixedFee: 0.0,
    notes: 'Illustrative wallet-style friction.',
  },
  {
    id: 'mintjewels',
    name: 'Physical retail jeweller',
    category: 'retail',
    badge: 'Premium + sellback haircut',
    buySpreadPct: 0.028,
    buyFeePct: 0.0,
    buyFixedFee: 0.0,
    annualCustodyPct: 0.0,
    sellSpreadPct: 0.04,
    sellFeePct: 0.0,
    sellExitFeePct: 0.0,
    sellFixedFee: 25,
    notes: 'Illustrative retail buy/sell spread stack.',
  },
  {
    id: 'mygoldwallet',
    name: 'Digital Gold App',
    category: 'retail',
    badge: 'Spread + vault assumptions',
    buySpreadPct: 0.022,
    buyFeePct: 0.0,
    buyFixedFee: 0.0,
    annualCustodyPct: 0.0018,
    sellSpreadPct: 0.022,
    sellFeePct: 0.0,
    sellExitFeePct: 0.0,
    sellFixedFee: 0.0,
    notes: 'Illustrative bundled digital gold stack.',
  },
  {
    id: 'izabullion',
    name: 'Bullion investment app',
    category: 'retail',
    badge: 'Mint fee + resale markdown',
    buySpreadPct: 0.032,
    buyFeePct: 0.0,
    buyFixedFee: 0.0,
    annualCustodyPct: 0.0,
    sellSpreadPct: 0.018,
    sellFeePct: 0.0,
    sellExitFeePct: 0.0,
    sellFixedFee: 35,
    notes: 'Illustrative app + physical premium assumptions.',
  },
  {
    id: 'rakbank',
    name: 'Major UAE Bank B (gold account)',
    category: 'banks',
    badge: 'Spread + custody',
    buySpreadPct: 0.02,
    buyFeePct: 0.0,
    buyFixedFee: 0.0,
    annualCustodyPct: 0.0035,
    sellSpreadPct: 0.02,
    sellFeePct: 0.0,
    sellExitFeePct: 0.0,
    sellFixedFee: 15,
    notes: 'Illustrative treasury-style spread assumptions.',
  },
  {
    id: 'adcb',
    name: 'Major UAE Bank C (premium tier)',
    category: 'banks',
    badge: 'Spread + higher custody assumption',
    buySpreadPct: 0.0225,
    buyFeePct: 0.0,
    buyFixedFee: 0.0,
    annualCustodyPct: 0.005,
    sellSpreadPct: 0.0225,
    sellFeePct: 0.0,
    sellExitFeePct: 0.0,
    sellFixedFee: 0.0,
    notes: 'Illustrative high custody scenario.',
  },
]
