# Generated by Django 5.2.13 on 2026-08-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('httpsms', 'httpSMS'), ('twilio', 'Twilio'), ('generic', 'Custom HTTP API')], default='httpsms', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('api_url', models.CharField(blank=True, default='', max_length=500)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('api_secret', models.CharField(blank=True, default='', max_length=500)),
                ('from_number', models.CharField(blank=True, default='', max_length=32)),
                ('auth_header', models.CharField(blank=True, default='x-api-key', max_length=80)),
                ('body_template', models.TextField(blank=True, default='', help_text='JSON body for generic provider. Placeholders: {to} {from} {content}')),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS provider config',
            },
        ),
    ]
