# Generated by Django 6.0.4 on 2026-04-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Cridora Admin'), ('vendor', 'Bullion Vendor'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='vendor_company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
