# Generated by Django 5.2.13 on 2026-04-19 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_kycdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('palladium', 'Palladium')], default='gold', max_length=20)),
                ('weight_grams', models.DecimalField(decimal_places=4, max_digits=10)),
                ('purity', models.CharField(default='999.9', max_length=20)),
                ('use_live_rate', models.BooleanField(default=True)),
                ('manual_rate_per_gram', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('buyback_per_gram', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('packaging_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_inclusive', models.BooleanField(default=False)),
                ('in_stock', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('stock_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['metal', 'weight_grams'],
            },
        ),
        migrations.CreateModel(
            name='VendorPricingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('silver_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('platinum_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('palladium_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('feed_url', models.URLField(blank=True)),
                ('feed_enabled', models.BooleanField(default=False)),
                ('feed_auth_header', models.CharField(blank=True, max_length=100)),
                ('feed_auth_value', models.CharField(blank=True, max_length=500)),
                ('feed_gold_field', models.CharField(blank=True, max_length=100)),
                ('feed_silver_field', models.CharField(blank=True, max_length=100)),
                ('feed_platinum_field', models.CharField(blank=True, max_length=100)),
                ('feed_palladium_field', models.CharField(blank=True, max_length=100)),
                ('feed_last_fetched', models.DateTimeField(blank=True, null=True)),
                ('feed_last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Pricing Config',
            },
        ),
    ]
