# Generated by Django 5.2.13 on 2026-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_catalogproduct_vendorpricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_images/%Y/%m/'),
        ),
    ]
