# Generated by Django 5.2.13 on 2026-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_catalogproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='gold_buyback_deduction',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='palladium_buyback_deduction',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='platinum_buyback_deduction',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='silver_buyback_deduction',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
