# Generated by Django 5.2.13 on 2026-04-21 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_catalogproduct_id_alter_customerbankdetails_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocumentSupersededSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport / National ID'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie with ID'), ('trade_license', 'Trade License'), ('company_registration', 'Company Registration Certificate'), ('owner_id', 'Owner / Director ID'), ('bank_proof', 'Bank Account Proof')], max_length=50)),
                ('file', models.FileField(upload_to='kyc_docs/superseded/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_snapshots_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superseded_kyc_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-superseded_at'],
            },
        ),
    ]
