# Generated by Django 5.2.13 on 2026-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_kycdocumentsupersededsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='home_spot_display_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='gold_purity_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='silver_purity_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='use_home_spot_gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='use_home_spot_silver',
            field=models.BooleanField(default=False),
        ),
    ]
