# Generated by Django 6.0.4 on 2026-04-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_home_spot_margin_purity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='gold_gram_rates_by_purity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendorpricingconfig',
            name='silver_gram_rates_by_purity',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
