# Generated by Django 5.2.13 on 2026-04-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_vendor_gram_rates_by_purity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='compliance_gates_at_payment',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
