# Generated by Django — ProductWishlistItem

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_vendor_gram_purity_maps_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='wishlisted_by',
                    to='users.catalogproduct',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='product_wishlist_items',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productwishlistitem',
            unique_together={('user', 'product')},
        ),
    ]
