# Generated by Django 5.2.13 on 2026-04-25 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_admin_vendor_bank_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofdaypayout',
            name='business_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='endofdaypayout',
            name='eod_business_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='endofdaypayout',
            name='holding_pct_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='eod_business_timezone',
            field=models.CharField(default='Asia/Dubai', max_length=64),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='eod_holding_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='EodVendorLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_revenue_aed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sell_deductions_aed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_before_hold_aed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('held_aed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payable_to_vendor_aed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending_bank', 'Awaiting admin bank record'), ('awaiting_vendor', 'Awaiting vendor bank confirmation'), ('closed', 'Closed (ledger final)')], default='pending_bank', max_length=20)),
                ('pdf_file', models.FileField(blank=True, max_length=500, null=True, upload_to='eod_ledgers/%Y/%m/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ledgers', to='users.endofdaypayout')),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='eod_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-eod__created_at', 'vendor_id'],
            },
        ),
        migrations.AddField(
            model_name='adminvendorpayout',
            name='eod_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout', to='users.eodvendorledger'),
        ),
        migrations.AddConstraint(
            model_name='eodvendorledger',
            constraint=models.UniqueConstraint(fields=('eod', 'vendor'), name='unique_eod_vendor_ledger'),
        ),
    ]
