# Generated by Django 5.2.13 on 2026-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_eod_treasury_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_vendor', 'Awaiting Vendor'), ('vendor_accepted', 'Accepted – Pending Payment'), ('paid', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('payment_expired', 'Payment timed out')], default='pending_vendor', max_length=20),
        ),
    ]
