# Generated by Django 5.2 — EOD per-vendor shop window

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_order_payment_checkout_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='eodvendorledger',
            name='window_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='eodvendorledger',
            name='window_end',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
