# Generated by Django 5.2.13 on 2026-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_id_bigautofield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminvendorpayout',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='payout_proofs/%Y/%m/'),
        ),
    ]
