# Generated by Django 5.2.13 on 2026-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_gram_buyback_maps_store_deductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eodvendorledger',
            name='status',
            field=models.CharField(choices=[('pending_bank', 'Awaiting admin bank record'), ('awaiting_vendor', 'Awaiting vendor bank confirmation'), ('pending_repayment', 'Awaiting vendor repayment to Cridora'), ('closed', 'Closed (ledger final)')], default='pending_bank', max_length=20),
        ),
    ]
