# Generated by Django 5.2 — sell order vendor response window

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_eodvendorledger_status_pending_repayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending_vendor', 'Awaiting Vendor'),
                    ('vendor_accepted', 'Payment Initiated'),
                    ('admin_approved', 'Admin Approved'),
                    ('completed', 'Completed'),
                    ('rejected', 'Rejected'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending_vendor',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='vendor_response_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
