# Generated by Django 5.2.13 on 2026-05-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_vendortoadminrepayment_eod_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalTickerDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('gold_24k_aed_per_gram', models.DecimalField(decimal_places=4, max_digits=14)),
                ('silver_999_aed_per_gram', models.DecimalField(decimal_places=4, max_digits=14)),
                ('copper_999_aed_per_gram', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('spot_payload_source', models.CharField(blank=True, default='', max_length=48)),
            ],
            options={
                'verbose_name': 'Metal ticker daily snapshot',
                'verbose_name_plural': 'Metal ticker daily snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
