# Generated by Django 5.2.13 on 2026-07-17 20:52

from django.db import migrations, models


def backfill_paid_at(apps, schema_editor):
    """Best-effort backfill: existing PAID orders have no paid_at, only created_at.
    We can't recover the true payment moment, so approximate with created_at rather
    than leaving these permanently excluded from every future EOD/treasury window."""
    Order = apps.get_model('users', 'Order')
    Order.objects.filter(status='paid', paid_at__isnull=True).update(paid_at=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_metal_ticker_daily_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_paid_at, migrations.RunPython.noop),
    ]
