# Generated by Django 5.2.13 on 2026-07-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_order_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbankdetails',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
