# Generated by Django 5.2.13 on 2026-07-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_kyc_bank_rejection_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='declared_value_aed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport / National ID'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie with ID'), ('trade_license', 'Trade License'), ('company_registration', 'Company Registration Certificate'), ('owner_id', 'Owner / Director ID'), ('bank_proof', 'Bank Account Proof'), ('insurance_certificate', 'Insurance Certificate (stock / bailee cover)'), ('vat_certificate', 'VAT Registration Certificate'), ('aml_registration', 'AML / DPMS Registration (goAML)'), ('business_address_proof', 'Proof of Business Address')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kycdocumentsupersededsnapshot',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport / National ID'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie with ID'), ('trade_license', 'Trade License'), ('company_registration', 'Company Registration Certificate'), ('owner_id', 'Owner / Director ID'), ('bank_proof', 'Bank Account Proof'), ('insurance_certificate', 'Insurance Certificate (stock / bailee cover)'), ('vat_certificate', 'VAT Registration Certificate'), ('aml_registration', 'AML / DPMS Registration (goAML)'), ('business_address_proof', 'Proof of Business Address')], max_length=50),
        ),
    ]
