# Generated by Django 5.2.13 on 2026-07-29 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_order_redemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fees_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='income_proof_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_hard_expiry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_window_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='psp_fee_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='requoted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='delivery_fee_priority_aed',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='delivery_fee_standard_aed',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='internal_kyc_threshold_aed',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='order_hard_expiry_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='packing_fee_aed',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='sellback_convenience_fee_flat_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='sellback_convenience_fee_pct',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='convenience_fee_aed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='leg1_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='leg2_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellorder',
            name='two_leg_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='aani_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='cumulative_purchase_month_key',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='cumulative_purchase_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='cumulative_purchase_total_this_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='income_proof_status',
            field=models.CharField(blank=True, default='none', help_text='none | pending | verified | rejected', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='residency_has_emirates_id',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport / National ID'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie with ID'), ('emirates_id', 'Emirates ID (front & back)'), ('passport_visa', 'Passport + UAE visa / entry stamp'), ('income_proof', 'Proof of income / source of funds'), ('trade_license', 'Trade License'), ('company_registration', 'Company Registration Certificate'), ('owner_id', 'Owner / Director ID'), ('bank_proof', 'Bank Account Proof'), ('insurance_certificate', 'Insurance Certificate (stock / bailee cover)'), ('vat_certificate', 'VAT Registration Certificate'), ('aml_registration', 'AML / DPMS Registration (goAML)'), ('business_address_proof', 'Proof of Business Address')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kycdocumentsupersededsnapshot',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport / National ID'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie with ID'), ('emirates_id', 'Emirates ID (front & back)'), ('passport_visa', 'Passport + UAE visa / entry stamp'), ('income_proof', 'Proof of income / source of funds'), ('trade_license', 'Trade License'), ('company_registration', 'Company Registration Certificate'), ('owner_id', 'Owner / Director ID'), ('bank_proof', 'Bank Account Proof'), ('insurance_certificate', 'Insurance Certificate (stock / bailee cover)'), ('vat_certificate', 'VAT Registration Certificate'), ('aml_registration', 'AML / DPMS Registration (goAML)'), ('business_address_proof', 'Proof of Business Address')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_vendor', 'Awaiting Vendor'), ('vendor_accepted', 'Accepted – Pending Payment'), ('paid', 'Completed (legacy)'), ('held', 'Held'), ('confirmed', 'Confirmed'), ('redemption_requested', 'Delivery requested'), ('redeemed', 'Redeemed'), ('sellback_requested', 'Sell-back requested'), ('sellback_funds_pending', 'Sell-back funds pending'), ('sold_back', 'Sold back'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('payment_expired', 'Payment timed out')], default='pending_vendor', max_length=32),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='status',
            field=models.CharField(choices=[('pending_vendor', 'Awaiting Vendor'), ('vendor_accepted', 'Payment Initiated'), ('admin_approved', 'Admin Approved'), ('sellback_funds_pending', 'Sell-back funds pending (Leg 1)'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_vendor', max_length=32),
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_tier', models.CharField(choices=[('standard_2day', 'Standard (2-day)'), ('priority_sameday', 'Priority (same-day)')], default='standard_2day', max_length=32)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending fee payment'), ('paid', 'Fee paid'), ('in_transit', 'In transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('courier_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='users.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_partner_ref', models.CharField(blank=True, default='', max_length=128)),
                ('verified_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('verified_purity', models.CharField(blank=True, default='', max_length=32)),
                ('verified_hallmark_ref', models.CharField(blank=True, default='', max_length=128)),
                ('otp_ref', models.CharField(blank=True, default='', max_length=64)),
                ('signature_ref', models.CharField(blank=True, default='', max_length=255)),
                ('video_ref', models.CharField(blank=True, default='', max_length=255)),
                ('duress_flag', models.BooleanField(default=False)),
                ('mismatch_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='users.deliveryrequest')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_handled', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_events', to='users.order')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], default='gold', max_length=16)),
                ('weight_grams', models.DecimalField(decimal_places=4, max_digits=12)),
                ('purity_estimate', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
