# Generated by Django 5.2.13 on 2026-07-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_v7_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='psp_fee_flat_aed',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='psp_fee_pct',
            field=models.DecimalField(decimal_places=2, default=2.6, max_digits=5),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='redemption_otp_ttl_seconds',
            field=models.PositiveIntegerField(default=900),
        ),
    ]
