# Generated by Django 5.2.13 on 2026-08-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_rate_ledger_movements_comparisons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport / National ID'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie with ID'), ('emirates_id', 'Emirates ID (front & back)'), ('emirates_id_front', 'Emirates ID — front'), ('emirates_id_back', 'Emirates ID — back'), ('passport_front', 'Passport — bio page'), ('passport_back', 'Passport — back / visa page'), ('passport_visa', 'Passport + UAE visa / entry stamp'), ('income_proof', 'Proof of income / source of funds'), ('trade_license', 'Trade License'), ('company_registration', 'Company Registration Certificate'), ('owner_id', 'Owner / Director ID'), ('bank_proof', 'Bank Account Proof'), ('insurance_certificate', 'Insurance Certificate (stock / bailee cover)'), ('vat_certificate', 'VAT Registration Certificate'), ('aml_registration', 'AML / DPMS Registration (goAML)'), ('business_address_proof', 'Proof of Business Address')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kycdocumentsupersededsnapshot',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport / National ID'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie with ID'), ('emirates_id', 'Emirates ID (front & back)'), ('emirates_id_front', 'Emirates ID — front'), ('emirates_id_back', 'Emirates ID — back'), ('passport_front', 'Passport — bio page'), ('passport_back', 'Passport — back / visa page'), ('passport_visa', 'Passport + UAE visa / entry stamp'), ('income_proof', 'Proof of income / source of funds'), ('trade_license', 'Trade License'), ('company_registration', 'Company Registration Certificate'), ('owner_id', 'Owner / Director ID'), ('bank_proof', 'Bank Account Proof'), ('insurance_certificate', 'Insurance Certificate (stock / bailee cover)'), ('vat_certificate', 'VAT Registration Certificate'), ('aml_registration', 'AML / DPMS Registration (goAML)'), ('business_address_proof', 'Proof of Business Address')], max_length=50),
        ),
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, default='', max_length=120)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('residency_status', models.CharField(blank=True, choices=[('', 'Not set'), ('resident', 'UAE resident'), ('visitor', 'Visitor')], default='', max_length=20)),
                ('emirates_id_number', models.CharField(blank=True, default='', max_length=32)),
                ('passport_number', models.CharField(blank=True, default='', max_length=32)),
                ('step1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('aml_result', models.JSONField(blank=True, default=dict)),
                ('aml_checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC profile',
            },
        ),
    ]
