# Generated by Django 5.2.13 on 2026-07-18 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorKycAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_kyc_grants', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.OneToOneField(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='manual_kyc_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor KYC access',
                'verbose_name_plural': 'Vendor KYC access',
            },
        ),
        migrations.CreateModel(
            name='VendorCustomerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_verifications', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_kyc_decisions', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='vendor_kyc__vendor__180884_idx'), models.Index(fields=['customer', 'status'], name='vendor_kyc__custome_5886fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'customer'), name='uniq_vendor_customer_verification')],
            },
        ),
        migrations.CreateModel(
            name='VendorKycAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('access_granted', 'Access granted'), ('access_revoked', 'Access revoked'), ('verification_requested', 'Verification requested'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('reverted', 'Reverted')], max_length=40)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_kyc_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_kyc_audit_as_customer', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_kyc_audit_as_vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='vendor_kyc__vendor__eec581_idx'), models.Index(fields=['customer', '-created_at'], name='vendor_kyc__custome_a03718_idx')],
            },
        ),
    ]
